### ISSUE TITLE
View Details Plugins

### ISSUE THREAD

**Issue by fobbert** [danieltj27/Dark-Mode#71] opened 2018-01-20 00:39 UTC
Hi, love the plugin and is getting better but I have one issue that is a pain.  If you go to the Plugins and view details the body text background is white and the text is a light grey, hard to read!
![wp darkmode-2018-01-20_11-37-30](https://user-images.githubusercontent.com/12842196/35177769-79fcdf78-fdd6-11e7-989d-364e0604e96e.jpg)

**Comment by danieltj27** [comment] 2018-01-20 11:42
Thanks for bringing this up. I'll look into this 👍

**Comment by danieltj27** [comment] 2018-02-11 13:05
Thanks again for the report. This was a regression due to some changes made to the styling cascade but is fixed in commit ce37eb8.

**Closed by danieltj27** 2018-02-11 13:05 UTC
Labels: BUG, GOOD FIRST ISSUE
